server:
  port: 8888
#port ${random.int[1024,65536]}
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#需要使用的配置文件
spring:
  redis:
    database: 0 #redis数据库索引（默认为0） redis一共有16个数据库默认使用第一个
    host: 127.0.0.1 #redis服务器地址
    port: 6379 #redis服务器连接端口
    password:  #redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-idle: 8 #连接池中的最大空闲连接 默认8
        min-idle: 0 #连接池中的最小空闲连接 默认0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/core?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #创建数据库时设置具体的database名称并且在Url路径后加上：?serverTimezone=GMT&useSSL=false在使用mabatis-generat前需要设置,serverTimezone=GMT在配置文件中有无均可，表示时区差
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    #.xml文件路径在resources包下时设置该配置mybatis:
    #  mapper-locations: classpath:generator/*.xml

logging:
  level:
    cn.itcast.bootstart: debug

auth:
  # authToken的过期时间
  authTokenExpire: 3600
  # refreshToken过期时间
  refreshTokenExpire: 7200
  # 放行的权限列表，采用小写的冒号分隔
  releaseUrl: /user/refreshToken
  # false表示用户单点登陆,true表示用户多点登录
  singleLanding: false